minetest.register_alias("decorations:casket", "decorations:malachite_casket")
minetest.register_alias("minerals:olivine", "minerals:olovine") 
minetest.register_alias("trees:ash_fence","fences:ash_fence")
minetest.register_alias("trees:aspen_fence","fences:aspen_fence")
minetest.register_alias("trees:birch_fence","fences:birch_fence")
minetest.register_alias("trees:mapple_fence","fences:mapple_fence")
minetest.register_alias("trees:chestnut_fence","fences:chestnut_fence")
minetest.register_alias("trees:pine_fence","fences:pine_fence")
minetest.register_alias("minerals:brown_coal", "minerals:lignite")
minetest.register_alias("ores:brown_coal","ores:lignite")
minetest.register_alias("minerals:lapis", "minerals:lazurite")
minetest.register_alias("default:chest", "trees:ash_chest")
minetest.register_alias("default:chest_locked", "trees:ash_chest_locked")