minetest.register_alias("decorations:casket", "decorations:malachite_casket")
minetest.register_alias("minerals:olovine", "minerals:olivine")
minetest.register_alias("trees:ash_fence","fences:ash_fence")
minetest.register_alias("trees:aspen_fence","fences:aspen_fence")
minetest.register_alias("trees:birch_fence","fences:birch_fence")
minetest.register_alias("trees:mapple_fence","fences:mapple_fence")
minetest.register_alias("trees:chestnut_fence","fences:chestnut_fence")
minetest.register_alias("trees:pine_fence","fences:pine_fence")
minetest.register_alias("minerals:brown_coal", "minerals:lignite")
minetest.register_alias("ores:brown_coal","ores:lignite")
minetest.register_alias("minerals:lapis", "minerals:lazurite")
minetest.register_alias("ores:lapis", "ores:lazurite")
minetest.register_alias("default:chest", "trees:ash_chest")
minetest.register_alias("default:chest_locked", "trees:ash_chest_locked")
minetest.register_alias("trees:mapple_chest","trees:maple_chest")
minetest.register_alias("trees:mapple_chest_locked","trees:maple_chest_locked")
minetest.register_alias("trees:mapple_planks","trees:maple_planks")
minetest.register_alias("trees:mapple_stick","trees:maple_stick")
minetest.register_alias("trees:mapple_sapling","trees:maple_sapling")
minetest.register_alias("trees:mapple_plank","trees:maple_plank")
minetest.register_alias("trees:mapple_log","trees:maple_log")
minetest.register_alias("trees:mapple_leaves","trees:maple_leaves")
minetest.register_alias("trees:mapple_leaves_autumn","trees:maple_leaves_autumn")
minetest.register_alias("trees:mapple_leaves_winter","trees:maple_leaves_winter")
minetest.register_alias("trees:mapple_trunk","trees:maple_trunk")
minetest.register_alias("trees:mapple_trunk_top","trees:maple_trunk_top")
minetest.register_alias("trees:mapple_ladder","trees:maple_ladder")
minetest.register_alias("trees:mapple_","trees:maple_")
minetest.register_alias("joiner_table:joiner_table_mapple","joiner_table:joiner_table_maple")
minetest.register_alias("scribing_table:scribing_table_mapple","scribing_table:scribing_table_maple")
minetest.register_alias("fences:mapple_fence", "fences:maple_fence")
for i = 0,15 do
	minetest.register_alias("fences:mapple_fence_"..i, "fences:maple_fence_"..i)
end
minetest.register_alias("doors:door_mapple", "doors:door_maple")
minetest.register_alias("doors:door_mapple_b_1", "doors:door_maple_b_1")
minetest.register_alias("doors:door_mapple_t_1", "doors:door_maple_t_1")
minetest.register_alias("doors:door_mapple_b_2", "doors:door_maple_b_2")
minetest.register_alias("doors:door_mapple_t_2", "doors:door_maple_t_2")
minetest.register_alias("decorations:bookshelf_mapple", "decorations:bookshelf_maple")
minetest.register_alias("trees:mapple_planks_slab", "trees:maple_planks_slab")
minetest.register_alias("trees:mapple_planks_slab_r", "trees:maple_planks_slab_r")
minetest.register_alias("trees:mapple_planks_stair", "trees:maple_planks_stair")
minetest.register_alias("trees:mapple_planks_stair_upside_down", "trees:maple_planks_stair_upside_down")
minetest.register_alias("default:clay_lump", "grounds:clay_lump")
minetest.register_alias("default:cobble", "default:stone_small_rock")
minetest.register_alias("default:cobbleblock", "default:stone_macadam")
minetest.register_alias("default:cobbleblock_flat", "default:stone_bricks")
minetest.register_alias("default:cobbleblock_flat_slab_r", "default:stone_bricks_slab_r")
minetest.register_alias("default:cobbleblock_flat_slab", "default:stone_bricks_slab")
minetest.register_alias("default:cobbleblock_flat_stair_r", "default:stone_bricks_stair_r")
minetest.register_alias("default:cobbleblock_flat_stair", "default:stone_bricks_stair")
minetest.register_alias("default:cobbleblock_flat_stair_upside_down_r", "default:stone_bricks_stair_upside_down_r")
minetest.register_alias("default:cobbleblock_flat_stair_upside_down", "default:stone_bricks_stair_upside_down")
minetest.register_alias("default:cobble_node", "default:stone_small_rock_node")
minetest.register_alias("default:coal_lump", "minerals:charcoal")
minetest.register_alias("ores:lignite","ores:lignite_in_default_stone")
minetest.register_alias("ores:anthracite","ores:anthracite_in_default_stone")
minetest.register_alias("ores:bituminous_coal","ores:bituminous_coal_in_default_stone")
minetest.register_alias("ores:magnetite","ores:magnetite_in_default_stone")
minetest.register_alias("ores:hematite","ores:hematite_in_default_stone")
minetest.register_alias("ores:limonite","ores:limonite_in_default_stone")
minetest.register_alias("ores:bismuthinite","ores:bismuthinite_in_default_stone")
minetest.register_alias("ores:cassiterite","ores:cassiterite_in_default_stone")
minetest.register_alias("ores:galena","ores:galena_in_default_stone")
minetest.register_alias("ores:garnierite","ores:garnierite_in_default_stone")
minetest.register_alias("ores:malachite","ores:malachite_in_default_stone")
minetest.register_alias("ores:native_copper","ores:native_copper_in_default_stone")
minetest.register_alias("ores:native_copper_desert","ores:native_copper_in_default_desert_stone")
minetest.register_alias("ores:native_gold","ores:native_gold_in_default_stone")
minetest.register_alias("ores:native_gold_desert","ores:native_gold_in_default_desert_stone")
minetest.register_alias("ores:native_silver","ores:native_silver_in_default_stone")
minetest.register_alias("ores:native_platinum","ores:native_platinum_in_default_stone")
minetest.register_alias("ores:sphalerite","ores:sphalerite_in_default_stone")
minetest.register_alias("ores:tetrahedrite","ores:tetrahedrite_in_default_stone")
minetest.register_alias("ores:lazurite","ores:lazurite_in_default_stone")
minetest.register_alias("ores:bauxite","ores:bauxite_in_default_stone")
minetest.register_alias("ores:cinnabar","ores:cinnabar_in_default_stone")
minetest.register_alias("ores:cryolite","ores:cryolite_in_default_stone")
minetest.register_alias("ores:graphite","ores:graphite_in_default_stone")
minetest.register_alias("ores:gypsum","ores:gypsum_in_default_stone")
minetest.register_alias("ores:jet","ores:jet_in_default_stone")
minetest.register_alias("ores:kaolinite","ores:kaolinite_in_default_stone")
minetest.register_alias("ores:kimberlite","ores:kimberlite_in_default_stone")
minetest.register_alias("ores:olovine","ores:olivine_in_default_stone")
minetest.register_alias("ores:petrified_wood","ores:petrified_wood_in_default_stone")
minetest.register_alias("ores:saltpeter","ores:saltpeter_in_default_stone")
minetest.register_alias("ores:satinspar","ores:satin_spar_in_default_stone")
minetest.register_alias("minerals:satinspar", "minerals:satin_spar")
minetest.register_alias("ores:selenite","ores:selenite_in_default_stone")
minetest.register_alias("ores:serpentine","ores:serpentine_in_default_stone")
minetest.register_alias("ores:sylvite","ores:sylvite_in_default_stone")
minetest.register_alias("ores:tenorite","ores:tenorite_in_default_stone")